config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root "blogs#index"
  resources :blogs do
   resources :votes, only: [:create, :destroy]
  end  # The priority is based upon order of creation: first created -> highest priority.

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :votes, dependent: :destroy

  def voted(user)
    self.votes.where(user_id: [user.id]).any?
  end 
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :votes, dependent: :destroy 

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  # rescue from pundit by going the function
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  private
  # alert user for unauthorized usage
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy, :create]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    authorize @blog
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    authorize @blog 
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    authorize @blog
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :publish)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
 before_action :authenticate_user!
 before_action :set_blog

 def create
   @vote = Vote.new
   @vote.blog = @blog
   @vote.user = current_user
   @vote.save
   redirect_to :back
 end

 def destroy
   @vote = @blog.votes.find(params[:id])
   @vote.destroy
   redirect_to :back
 end

 private
 def set_blog
    @blog = Blog.find(params[:blog_id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="row">
 <div class="col s12">
   <div class="card-panel">
     <%= form_for(@blog) do |f| %>
     <!-- blog title -->
     <div class="input-field">
       <%= f.label :title %>
       <%= f.text_field :title, required: true, autofocus: true %>
     </div>
     <!-- blog content -->
     <div class="input-field">
       <%= f.label :content %>
       <%= f.cktext_area :content, required: true, class: "materialize-textarea"%>
     </div>
     <!-- blog publish -->
     <div class="input-field">
       <%= f.check_box :publish, class: "filled-in" %>
       <%= f.label :publish %>
     </div>
     <!-- Submit form -->
     <div class="input-field center">
       <%= f.submit button, class: "btn" %>
     </div>
     <% end %>
   </div>
 </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
 <h1 class="center">Edit <%= @blog.title.truncate(15) %></h1>
 <%= render partial:'form', locals: {button: "Save Blog"} %>
</div> 

app/views/blogs/index.html.erb
<div class="container">
 <!-- Fixed New blog button -->
 <div class="fixed-action-btn" style="top: 50px; right: 24px;">
   <a class="btn-floating btn-large red" href="<%= new_blog_path %>">
     <i class="large material-icons">add</i>
   </a>
 </div>
 <!-- Header of index-->
 <h1 class="center">MyBlog</h1>
  <!-- Indexes -->
  <div class="row">
    <!-- Handling each blog separate -->
    <% @blogs.each do |blog| %>
    <%= link_to blog_path(blog) do %>
    <div class="col s12 m4">
      <div class="card">
        <div class="card-content black-text">
          <span class="card-title black-text"><strong><%= blog.title.truncate(20)%></strong>
            <% if user_signed_in? && blog.voted(current_user) %>
            <span class="center"><%= link_to '<i class="material-icons"
            style="color: #FF0000;">favorite</i>'.html_safe, blog_vote_path(blog,blog.votes.where(user_id: current_user.id).first.id),
            method: :delete %> <%= blog.votes.count %></span>
            <% else %>
            <span class="center"><%= link_to '<i class="material-icons"
            style="color: #FF0000">favorite_border</i>'.html_safe,blog_votes_path(blog), method: :post %> <%= blog.votes.count %></span>
            <% end %>
          </span>
            <% require 'rubygems' %>
            <% require 'nokogiri' %>
            <div><%= Nokogiri::HTML(blog.content).text.truncate(300, separator: ' ')%></div>
        </div>
      </div>
    </div>
   <% end %>
   <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
<h1 class="center">New Blog</h1>
<%= render partial:'form', locals: {button: "Create Blog"} %>
</div> 

app/views/blogs/show.html.erb
<div class="container">
 <div class="row">
   <div class="col s12">
     <div class="card-panel">
       <h1 class="center"><%= @blog.title %></h1>
       <% if user_signed_in? && @blog.voted(current_user) %>
        <div class="center"><%= link_to '<i class="material-icons"
        style="color: #FF0000;">favorite</i>'.html_safe, blog_vote_-
        path(@blog,@blog.votes.where(user_id: current_user.id).first.id), method::delete %> <%= @blog.votes.count %></div>
        <% else %>
        <div class="center"><%= link_to '<i class="material-icons"
        style="color: #FF0000">favorite_border</i>'.html_safe, blog_votes_path(@blog), method: :post %> <%= @blog.votes.count %></div>
        <% end %>
       <hr/>
      <p><%= raw @blog.content %></p>
     </div>
   </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initialscale=1.0"/>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--Import Google Icon Font-->
 <link href="http://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/topNav' %>
<main>
 <%= yield %>
</main> 
<%= render 'shared/footer' %>


</body>
</html>

app/views/shared/_footer.html.erb
<nav style="background-color: rgba(158, 158, 158, 0.21);">
 <div class="nav-wrapper">
 <a href=" " style="color: #9E9E9E; marginright:
10px;" class="right">Copyright &copy; Sara Yazdani</a>
 </div>
</nav>

app/views/shared/_navElements.html.erb
<li class="<%= "active" if controller_name == "blogs" %>"><%= link_to "Blogs", root_path %></li>
<% if user_signed_in? %>
 <li class="<%= "active" if current_page?(edit_user_registration_path) %>"><%= link_to "Edit Profile", edit_user_registration_path %></
li>
 <li><%= link_to "Log Out", destroy_user_session_path,method: :delete %></li>
<% else %>
 <li class="<%= "active" if current_page?(new_user_session_path)%>"><%= link_to "Log In", new_user_session_path %></li>
 <li class="<%= "active" if current_page?(new_user_registration_path) %>"><%= link_to "Sign Up", new_user_registration_path %></li>
<% end %>

app/views/shared/_topNav.html.erb
<nav style="background-color: #ecc400;">
 <div class="nav-wrapper">
 <a href="<%= root_path %>" class="brand-logo">MyBlog</a>
 <a href="#" data-activates="mobile-demo" class="button-collapse"><i
class="material-icons">menu</i></a>
 <ul class="right hide-on-med-and-down">
   <%= render "shared/navElements" %> 
 </ul>
 <ul class="side-nav" id="mobile-demo">
   <%= render "shared/navElements" %>
 </ul>
 </div>
</nav>